(ert-deftest test-org-export-website-headline ()
  (should (equal (org-export-website-headline '(headline (:raw-value "foo" :level 1)) nil nil)
                 "<h1>foo</h1>"))
  (should (equal (org-export-website-headline '(headline (:raw-value "bar" :level 2)) nil nil)
                 "<h2>bar</h2>"))
  (should (equal (org-export-website-headline '(headline (:raw-value "baz" :level 3)) "Some content" nil)
                  "<h3>baz</h3>\n\nSome content")))
